allowBuilds:
  '@firebase/util': false
  '@nestjs/core': false
  '@openapitools/openapi-generator-cli': true
  '@scarf/scarf': false
  '@swc/core': true
  cpu-features: false
  esbuild: true
  msgpackr-extract: false
  protobufjs: false
  ssh2: false
  tree-sitter: true
